# -*- mode: python ; coding: utf-8 -*-
# PyInstaller spec for the AdaptiveLearner launcher (Windows, Linux, macOS).
#
# Build:  poetry run pyinstaller adaptive-learner-launcher.spec
# Output:
#   Windows: dist/adaptive-learner-launcher.exe (single-file, windowed, icon embedded)
#   Linux:   dist/adaptive-learner-launcher (ELF binary)
#   macOS:   dist/AdaptiveLearner Launcher.app (bundle, icon if adaptive_learner.icns exists)

import os
import re
import sys
from pathlib import Path

# --- Build-time version injection ------------------------------------
# Read the target AdaptiveLearner version from backend/pyproject.toml and
# write a generated module the launcher imports. backend/pyproject.toml
# is the canonical Python source-of-truth; the launcher's frozen binary
# bakes the value in at build time so it is offline-evaluable in
# production. The generated file is gitignored.
#
# PyInstaller exec()s spec files via build_main.exec(code, spec_namespace),
# which does NOT define ``__file__``. PyInstaller injects ``SPECPATH``
# (directory containing the spec file) into the namespace instead; use
# that as the anchor.

_spec_dir = Path(SPECPATH).resolve()
_repo_root = _spec_dir.parent
_backend_pyproject = _repo_root / "backend" / "pyproject.toml"
_match = re.search(
    r'^version\s*=\s*"([^"]+)"',
    _backend_pyproject.read_text(encoding="utf-8"),
    re.MULTILINE,
)
if _match is None:
    raise SystemExit(
        f"FATAL: cannot read version from {_backend_pyproject}"
    )
_target_version = _match.group(1)

_build_info = (
    _spec_dir / "adaptive_learner_launcher" / "_build_info.py"
)
_build_info.write_text(
    "# AUTO-GENERATED at PyInstaller build time. Do not edit; regenerate "
    "via\n# `poetry run pyinstaller adaptive-learner-launcher.spec`. See spec for "
    "source.\n"
    f'ADAPTIVE_LEARNER_TARGET_VERSION = "{_target_version}"\n',
    encoding="utf-8",
)

block_cipher = None


a = Analysis(
    ["adaptive_learner_launcher/__main__.py"],
    pathex=[],
    binaries=[],
    datas=[
        # JSON i18n catalogs read via importlib.resources at runtime.
        # Without this, the frozen binary loses every translation.
        ("adaptive_learner_launcher/locales", "adaptive_learner_launcher/locales"),
    ],
    hiddenimports=[],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[
        # Keep the bundle lean: drop anything we definitely do not import.
        "numpy",
        "pandas",
        "matplotlib",
        "scipy",
        "PIL",  # Pillow is only for the icon-generation script, not runtime.
    ],
    noarchive=False,
    cipher=block_cipher,
)

pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.zipfiles,
    a.datas,
    [],
    name="adaptive-learner-launcher",
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=False,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=False,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    # Windows-only: embed icon + version metadata. On non-Windows builds
    # (used only for local smoke by Linux devs), these kwargs are ignored.
    icon=["adaptive_learner.ico"] if sys.platform == "win32" else None,
    version="version_info.txt" if sys.platform == "win32" else None,
)


# macOS .app bundle. Skipped on Windows and Linux.
# The icon file "adaptive_learner.icns" is generated by the macOS CI workflow
# (iconutil is macOS-only) before PyInstaller runs. If the file is
# missing, the bundle builds without a custom icon and falls back to
# PyInstaller's default.
if sys.platform == "darwin":
    app = BUNDLE(
        exe,
        name="AdaptiveLearner Launcher.app",
        icon="adaptive_learner.icns" if os.path.exists("adaptive_learner.icns") else None,
        bundle_identifier="com.adaptive_learner.launcher",
        info_plist={
            "CFBundleName": "AdaptiveLearner Launcher",
            "CFBundleDisplayName": "AdaptiveLearner Launcher",
            "CFBundleVersion": "0.33.0",
            "CFBundleShortVersionString": "0.33.0",
            "NSHighResolutionCapable": True,
            "NSRequiresAquaSystemAppearance": False,
        },
    )
