/**
 * ${class_name}${page_suffix} - stub page generated by the bootstrap script.
 *
 * TODO: implement the real UI. The api client, types, db schema, and
 * stale-while-revalidate hooks are wired; this component is intentionally
 * minimal so the build stays green until the human / AI session that
 * fills it in.
 */

import {use${entities_pascal}} from "../hooks/use${pascal_name}";

export default function ${class_name}${page_suffix}() {
    const {data, loading, error} = use${entities_pascal}();

    return (
        <main data-testid="${plural}-${page_kind}-page">
            <h1>${class_name}${page_suffix}</h1>
            <p>TODO: implement ${class_name} ${page_kind} UI.</p>
            {loading && <p>Loading...</p>}
            {error && <p role="alert">Error: {error.message}</p>}
            {!loading && !error && (
                <p>{data.length} ${plural} cached.</p>
            )}
        </main>
    );
}
